package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type enumDef struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Values      []string `json:"values"`
}

func generateEnum(srcPath, outDir string) error {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return err
	}

	var def enumDef
	if err := json.Unmarshal(data, &def); err != nil {
		return fmt.Errorf("parsing %s: %w", srcPath, err)
	}

	typeName := toPascalCase(def.Name)
	outFile := filepath.Join(outDir, toSnakeCase(def.Name)+".go")

	var b strings.Builder
	b.WriteString("// Code generated by traust-contracts codegen. DO NOT EDIT.\n\n")
	b.WriteString("package enums\n\n")

	if def.Description != "" {
		fmt.Fprintf(&b, "// %s — %s\n", typeName, def.Description)
	}
	fmt.Fprintf(&b, "type %s string\n\n", typeName)

	fmt.Fprint(&b, "const (\n")
	for _, val := range def.Values {
		constName := typeName + toPascalCase(val)
		fmt.Fprintf(&b, "\t%s %s = %q\n", constName, typeName, val)
	}
	fmt.Fprint(&b, ")\n\n")

	fmt.Fprintf(&b, "// %sValues returns all valid %s values.\n", typeName, typeName)
	fmt.Fprintf(&b, "func %sValues() []%s {\n", typeName, typeName)
	fmt.Fprintf(&b, "\treturn []%s{\n", typeName)
	for _, val := range def.Values {
		constName := typeName + toPascalCase(val)
		fmt.Fprintf(&b, "\t\t%s,\n", constName)
	}
	fmt.Fprint(&b, "\t}\n")
	fmt.Fprint(&b, "}\n")

	return formatAndWrite(outFile, []byte(b.String()))
}

func toPascalCase(s string) string {
	var result strings.Builder
	capitalize := true
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' || r == ':' {
			capitalize = true
			continue
		}
		if capitalize {
			result.WriteRune(unicode.ToUpper(r))
			capitalize = false
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

func toSnakeCase(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "-", "_"), " ", "_")
}
